RuntimeError: The size of tensor a (38) must match the size of tensor b (40) at non-singleton dimension 3 the above is the error that happen to solve this it need to resize the output of decoder it happen because of Imperfect reversal of convolutions during upsampling in the decoder.